var cocktails = [];

function Cocktail(img, name, background, ingredients, steps) {
    this.img = img;
    this.name = name;
    this.background = background;
    this.ingredients = ingredients;
    this.steps = steps;
};

function createCocktail(img, name, background, ingredients, steps){

        let fullImg = `./img/drink-${img}.jpg`;
        let cocktail = new Cocktail(fullImg, name, background, ingredients, steps);

        cocktails.push(cocktail);
};

createCocktail(0, 'Gin & Tonic', 'If you can say it, you can make it. Right? Right. But also, not exactly. The two-ingredient cocktail requires your undivided attention. From glassware to garnish to style of gin and spirit proof, everything should be carefully considered when mixing a G&T.', '<div class="ingredient-list"><li class="ingredients">2 ounces gin</li><li class="ingredients">4 ounces tonic water</li><li class="ingredients">Garnish: 2 lime wheels</li></div>', '<div class="steps-list"><li class="steps">Fill a highball glass with ice, then add the gin.</li><li class="steps">Top with the tonic water and gently stir.</li><li class="steps">Garnish with lime wheels.</li></div>' );
createCocktail(1, 'Sangria', 'Sangria comes to us by way of Spain and Portugal and has a long and rich history that dates back to the Middle Ages and was originally aged wine mixed with fruit and spices, such as cinnamon.', '<div class="ingredient-list"><li class="ingredients">1/2 medium apple (cored, skin on, chopped into small pieces)</li><li class="ingredients">1/2 medium orange (rind on, sliced into small pieces, large seeds removed</li><li class="ingredients">3-4 Tbsp organic brown sugar (or 3 Tbsp (37.5 g) organic cane sugar as original recipe is written)</li><li class="ingredients">3/4 cup orange juice (plus more to taste)</li><li class="ingredients">1/3 cup brandy (plus more to taste)</li><li class="ingredients">750 ml bottle dry Spanish red wine</li><li class="ingredients">~1 cup Ice to chill</li></div>', '<div class="steps-list"><li class="steps">Add apples, oranges, and sugar to a large pitcher and muddle with a muddler or wooden spoon for 45 seconds.</li><li class="steps">Add orange juice and brandy and muddle again to combine for 30 seconds.</li><li class="steps">Add red wine and stir to incorporate, then taste and adjust flavor as needed. I added a bit more brandy, orange juice and brown sugar. Stir to combine.</li><li class="steps">Add ice and stir once more to chill. Serve as is, or with a bit more ice. Garnish with orange segments (optional).</li><li class="steps">Store leftovers covered in the refrigerator for up to 48 hours, though best when fresh.</li></div>');
createCocktail(2, 'Moscow Mule', 'The Moscow Mule is a classic vodka-based cocktail that is popular for good reason: It’s delicious, refreshing and a snap to make. Just speaking the name of the drink conjures images of the ice-cold copper mug that is the de rigueur vessel for the Moscow Mule.', '<div class="ingredient-list"><li class="ingredients">2 oz. vodka</li><li class="ingredients">1/2 oz. lime juice, freshly squeezed</li><li class="ingredients">6 oz. ginger beer</li></div>', '<div class="steps-list"><li class="steps">Squeeze lime juice into a copper mug (or a Collins glass) and drop in the spent shell.</li><li class="steps">Add ice cubes, then pour in the vodka and fill with cold ginger beer.</li><li class="steps">Serve with a stirring rod.</li></div>');
createCocktail(3, 'Whiskey Sour', 'Spirit, citrus and sugar—the original big three—combine to form the classic sour, one of the oldest types of cocktails. The category includes the Whiskey Sour, which has sated thirsty drinkers for more than one and a half centuries. It’s unknown exactly when the cocktail was conceived (or who was the architect), but its history stretches back to the Lincoln administration, and the first printed recipe appeared circa 1862 in the famed “Jerry Thomas Bartenders Guide."','<div class="ingredient-list"><li class="ingredients">2 ounces bourbon</li><li class="ingredients">3/4 ounce lemon juice, freshly squeezed</li><li class="ingredients">1/2 ounce simple syrup</li><li class="ingredients">1/2 ounce egg white (optional)</li><li class="ingredients">Garnish: Angostura bitters</li></div>', '<div class="steps-list"><li class="steps">Add bourbon, lemon juice, simple syrup and egg white, if using, to a shaker and dry-shake for 30 seconds without ice.</li><li class="steps">Add ice and shake again until well-chilled.</li><li class="steps">Strain into a coupe glass.</li><li class="steps">Garnish with 3 or 4 drops of Angostura bitters.</li></div>');
createCocktail(4, 'Paloma', 'The paloma is a thirst-quenching tequila cocktail that\'s very easy to mix up. A favorite drink from Mexico, it is equally popular worldwide and one of the best ways to show off a great tequila. "Paloma" is the Spanish word for "dove," and it\'s a fitting name for this sparkling grapefruit drink.', '<div class="ingredient-list"><li class="ingredients">2 ounces tequila</li><li class="ingredients">2 ounces fresh grapefruit juice, plus wedges for garnish</li><li class="ingredients">2 ounces sparkling water</li><li class="ingredients">1/2 ounce lime juice</li><li class="ingredients">1/4 ounce agave nectar or simple syrup, or to taste</li><li class="ingredients">Coarse sea salt, for the rim of the glasses</li><li class="ingredients">Ice</li></div>', '<div class="steps-list"><li class="steps">Salt the rim of the glass by rubbing a grapefruit wedge around the edge and dipping it onto a small plate of salt.</li><li class="steps">Mix the tequila, grapefruit juice, sparkling water, lime juice, and agave nectar into the glass. </li><li class="steps">Fill the remainder of the glass with ice.</li><li class="steps">Adjust sweetness to taste. Garnish with grapefruit wedge.</li></div>');
